### ISSUE TITLE
S20: As a player, I want to have to have enjoyable and playful experience to enjoy the game. 

### ISSUE THREAD

**Issue by UZH-JingCao** [sopra-fs23-group-21/sopra-fs23-group-21-server#125]
# Acceptance Criteria:

- The game must have sound effects and/or a soundtrack that enhances the player's experience and adds to the overall enjoyment of the game.
- The game must use bright and engaging colors, and incorporate animations that are visually appealing and engaging.

# Development Tasks:

- [ ] sopra-fs23-group-21/sopra-fs23-group-21-server#126
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#127
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#128
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#45
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#134
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#42
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#43
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#46
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#47
