### ISSUE TITLE
S17: As a registered user, I want to be able to login the system so that I can play the game.

### ISSUE THREAD

**Issue by UZH-JingCao** [sopra-fs23-group-21/sopra-fs23-group-21-server#40]
# Acceptance Criteria:

- If the username and password are valid, the system shall log in to the user and redirect them to the game page.
- If the username and password are invalid, the system shall display an error message.
- User should be able to logout

# Development Task:

- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#41 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#43
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#50 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#29 
- [x] #137
- [x] #139 
- [x] #140
- [x] #141
- [x] #142
- [x] #144
