### ISSUE TITLE
S18: As a logged-in user, I want to edit my own user profile to set/update my personal information.

### ISSUE THREAD

**Issue by UZH-JingCao** [sopra-fs23-group-21/sopra-fs23-group-21-server#46]
# Acceptance Criteria

- A registered user can only change their own profile and not profiles of other users.
- A registered user can change the password

# Development Tasks

- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#45
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#49 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#17 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#30 
- [x] #122 
- [x] #123
- [x] #132
- [x] #143
- [x] #149
