### ISSUE TITLE
S1:As a player, I want the game to prepare a deck of 54 cards (including Jokers), so that the game follows the standard Doudizhu rules and is ready for play.

### ISSUE THREAD

**Issue by UZH-JingCao** [sopra-fs23-group-21/sopra-fs23-group-21-server#6]
# Acceptance Criteria:

-  There are 54 cards in total

-  (2，3，4，5，6，7，8，9，10，J, Q, K, A)*4 + Two Jokers

# Deployment Task:

- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#18
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#19
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#20
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#22
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#51 
- [x]  sopra-fs23-group-21/sopra-fs23-group-21-server#60 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#12
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#21 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#19 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#22 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#23 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#26 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#32 
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#41
- [x] #130

**Comment by weimin3** [comment]
Define combination types:single cards, double cards,triple cards,triple cards and one, chain,consecutive double cards, double three,four and three,bomb,double jorkers.
