### ISSUE TITLE
S2: As a player, I want the game to shuffle the deck and deal 17 cards to farm player and deal 20 cards to Landlord player, so that everyone starts with a random hand.The landlord is determined through election.

### ISSUE THREAD

**Issue by UZH-JingCao** [sopra-fs23-group-21/sopra-fs23-group-21-server#7]
# Acceptance Criteria:

- [x] The user gets the card randomly
- [x] Farmer users receive 17 cards
- [x] The landlord user gets 20 cards
- [x] The landlord is determined through the election.
- [x] The players can see every role's number of remaining cards in the game room.

# Development Task:

- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#25
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#26
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#27
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#27
- [x] #133
