### ISSUE TITLE
S3: As a player, I want to create the game room, join a game room, and start the game when we have three players in the same game room.

### ISSUE THREAD

**Issue by UZH-JingCao** [sopra-fs23-group-21/sopra-fs23-group-21-server#8]
# Acceptance Criteria:

- [x] When the number of players is 3, each player will receive a corresponding number of cards, and the number of playing cards in the deck becomes 0

- [x] Sort the cards in the player's hand in the order of 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A, 2, small joker, big joker.

# Development Task:

- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#65
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#66
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#67
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#68
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#69
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#70
- [x] sopra-fs23-group-21/sopra-fs23-group-21-server#71
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#24
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#38
- [x] sopra-fs23-group-21/sopra-fs23-group-21-client#39
- [x] #107
- [x] #108
- [x] #115
- [x] #135
